#!/usr/bin/env python
# -*- coding: utf-8 -*-
import telebot
from telebot import apihelper

token = '765877754:AAGv-U_uGBvRc08_vxoRoW248dTnMhQS_jA'

bot = telebot.TeleBot(token)
#apihelper.proxy = {'http':'socks5://swcbbabh:aYEbh6q5gQ@rey.vivalaresistance.info:3306'}

apihelper.proxy = {'https':'socks5://swcbbabh:aYEbh6q5gQ@rey.vivalaresistance.info:3306'}


@bot.message_handler(content_types=['photo'])  
def downloader(message):
	try:
		file_info = bot.get_file(message.photo[len(message.photo)-1].file_id)
		downloaded_file = bot.download_file(file_info.file_path)
      
		src='tmp/'+file_info.file_path;
		with open(src, 'wb') as new_file:
			new_file.write(downloaded_file)
		bot.reply_to(message,"Фото добавлено") 
		
		

	except Exception as e:
		bot.reply_to(message,e )	
if __name__ == '__main__':
    bot.polling(none_stop=True)
